# Generated by Django 4.2.16 on 2024-11-15 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=250)),
                ('eventTiming', models.TimeField()),
                ('name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=250)),
                ('phone', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('adultsCount', models.IntegerField()),
                ('childrenCount', models.IntegerField()),
                ('paymentID', models.CharField(max_length=250, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('eventName', models.CharField(max_length=250)),
                ('eventTiming', models.TimeField()),
                ('eventCapacity', models.IntegerField()),
                ('eventPriceAdult', models.FloatField()),
                ('eventPriceChild', models.FloatField()),
                ('eventStatus', models.BooleanField()),
                ('eventDisplay', models.BooleanField()),
            ],
        ),
    ]
